### ISSUE TITLE
"TypeError: Cannot read property 'tapAsync' of undefined" after update to html-webpack-plugin v4 from v3

### ISSUE THREAD

**Issue by srghma** [octalmage/html-webpack-root-plugin#3]
```
/home/srghma/projects/purescript-halogen-mdl/node_modules/html-webpack-root-plugin/lib/plugin.js:30
      compilation.hooks.htmlWebpackPluginAfterHtmlProcessing.tapAsync(
                                                             ^

TypeError: Cannot read property 'tapAsync' of undefined
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/html-webpack-root-plugin/lib/plugin.js:30:62
    at SyncHook.eval [as call] (eval at create (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:631:26)
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:662:28)
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:529:11)
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/CachePlugin.js:50:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:5:1)
    at AsyncSeriesHook.lazyCompileHook (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/Hook.js:154:20)
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/home/srghma/projects/purescript-halogen-mdl/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/home/srghma/projects/purescript-halogen-mdl/node_modules/webpack/lib/Compiler.js:312:24)
    at processOptions (/home/srghma/projects/purescript-halogen-mdl/node_modules/webpack-cli/bin/cli.js:353:14)
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/home/srghma/projects/purescript-halogen-mdl/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/srghma/projects/purescript-halogen-mdl/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/srghma/projects/purescript-halogen-mdl/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

```
  "devDependencies": {
    "autoprefixer": "^9.7.4",
    "css-loader": "^3.4.2",
    "html-webpack-plugin": "^4.0.1",
    "html-webpack-root-plugin": "^0.10.0",
    "mini-css-extract-plugin": "^0.9.0",
    "postcss-loader": "^3.0.0",
    "precss": "^4.0.0",
    "purs-loader": "^3.7.1",
    "ramda": "^0.27.0",
    "ramda-adjunct": "^2.26.0",
    "style-loader": "^1.1.3",
    "terser-webpack-plugin": "^2.3.5",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3",
    "webpack-merge": "^4.2.2",
    "workbox-webpack-plugin": "^5.1.1"
  }
```

```
  plugins: [
    new HtmlWebpackPlugin({
      title: 'test',
    }),
    new HtmlWebpackRootPlugin(), // if commented - error disappears
  ]
```

**Comment by srghma** [comment]
full config

```
'use strict';

const RA = require('ramda-adjunct')

const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlWebpackRootPlugin = require('html-webpack-root-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

const webpack = require('webpack');

const { env, root, isWebpackDevServer } = require('./lib')

module.exports = {
  // mode: 'development',
  mode: env('development', 'production'),

  bail: true,
  profile: true,
  stats: {
    colors: true,
  },
  context: root,
  devtool: env('cheap-module-source-map', false),

  devServer: {
    hot: true,
    port: 3000,
    stats: 'errors-only',
    disableHostCheck: true,   // That solved it
  },

  module: {
    rules: [
      {
        // For pure CSS (without CSS modules)
        test: /\.css$/i,
        exclude: /\.module\.css$/i,
        use: [ env("style-loader", MiniCssExtractPlugin.loader), "css-loader"]
      },
      {
        // For CSS modules
        test: /\.module\.css$/i,
        use: [
          env("style-loader", MiniCssExtractPlugin.loader),
          {
            loader: 'css-loader',
            options: {
              modules: true,
            },
          },
        ],
      },
      {
        test: /\.purs$/,
        use: [
          {
            loader: 'purs-loader',
            options: {
              src: [
                'src/**/*.purs',
                'docs-src/**/*.purs'
              ],
              spago: true,
              watch: isWebpackDevServer,
              pscIde: true
            }
          }
        ]
      },
      {
        test: /\.(png|jpg|gif)$/i,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 8192,
            },
          },
        ],
      },
    ]
  },

  resolve: {
    modules: [ 'node_modules' ],
    extensions: [ '.purs', '.js']
  },

  plugins: RA.compact([
    new HtmlWebpackPlugin({
      title: 'purescript-halogen-mdl',
    }),
    // new HtmlWebpackRootPlugin(),

    env(null, new MiniCssExtractPlugin()),

    // (
    //   isWebpackDevServer ?
    //   null :
    //   function () {
    //     this.plugin('done', function(stats) {
    //       process.stderr.write(stats.toString('errors-only'))
    //     })
    //   }
    // ),
  ])
};

```

```
const merge = require('webpack-merge')
const path = require('path')

const shared = require('./shared')
const { env, root, isWebpackDevServer } = require('./lib')

module.exports = merge(shared, {
  target: 'node',

  output: {
    path: path.resolve(root, 'docs'),
    filename: "server.js"
  },

  entry: path.resolve(root, "./docs-src/server.entry.js"),
})
```

**Comment by srghma** [comment]
https://github.com/numical/style-ext-html-webpack-plugin/pull/45/files

**Comment by Vladi4-gh** [comment]
Same thing dude. Latest WebPack 4.

**Comment by dominikwilkowski** [comment]
Same issue here.
From the issue this might help fix this:

https://github.com/jantimon/html-webpack-plugin/issues/1049#issuecomment-423142837
